name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18, 20, 21]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Turborepo cache
        uses: dtinth/setup-github-actions-caching-for-turbo@v1
      - if: matrix.node-version == 20
        name: Check code style
        run: pnpm format:check
      - name: Build
        run: pnpm turbo build
      - name: Check types
        run: pnpm turbo types:check
      - name: Run tests
        run: pnpm test
      - if: matrix.node-version == 20
        name: Send bundle stats and build information to RelativeCI
        uses: relative-ci/agent-action@v2
        with:
          key: ${{ secrets.RELATIVE_CI_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
          webpackStatsFile: ./packages/api-reference/dist/browser/webpack-stats.json

  screenshots:
    runs-on: ubuntu-20.04
    needs: ci
    strategy:
      matrix:
        url: ['https://github.com']

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Turborepo cache
        uses: dtinth/setup-github-actions-caching-for-turbo@v1
      - name: Build
        run: pnpm turbo build
      - name: Take screenshots
        id: screenshot
        uses: swinton/screenshot-website@v1.x
        with:
          source: ${{ matrix.url }}
          destination: screenshot.png
      - name: Comment on PR
        uses: gavv/pull-request-artifacts@v2
        with:
          # Commit hash that triggered PR
          commit: ${{ github.event.pull_request.head.sha }}

          # Token for current repo (used to post PR comment)
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          # Optional, uncomment to upload to another repository
          #artifacts-token: ${{ secrets.ANOTHER_TOKEN_WITH_PUSH_ACCESS }}
          #artifacts-repo: some/repository_name

          # Optional, uncomment to upload artifacts to specific branch, otherwise
          # the default branch is used.
          # Note that usually the main branch is protected by rules, so it's not
          # possible to upload there.
          # Perhaps, the best solution is to create an empty unprotected branch
          # dedicated for artifacts.
          # See README for details.
          #artifacts-branch: some_branch

          # Optional, uncomment to preserve artifacts path and add prefix.
          # By default artifacts are uploaded to "pr<pr_number>-<artifact_basename>".
          # With options below, artifacts will be uploaded to "my_prs/<pr_number>/<artifact_path>".
          #artifacts-prefix: "my_prs/${{ github.event.number }}/"
          #preserve-path: true

          # Optional, uncomment to use non-default title and style.
          #comment-title: "My artifacts"
          #comment-message: "My message"
          #comment-style: list

          # Whitespace-separated list of files to upload
          artifacts: |
            screenshot.png
      # - name: Comment on PR
      #   uses: tonyhallett/artifacts-url-comments@v1.1.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     prefix: '**Preview**'
      #     format: name
      #     addTo: pull
      # - name: Comment on PR
      #   uses: thollander/actions-comment-pull-request@v2
      #   with:
      #     message: ${{ steps.screenshot.outputs.path }}
      #     comment_tag: screenshots
